### ISSUE TITLE
[FEAT] 인장 이미지 저장하는 필드 API 에 추가하기

### ISSUE THREAD

**Issue by cottonpup** [ramgee-zzik-nabi/application#38]
# 작업내용
프로필 이미지를 저장하는 필드를 API 에 추가하기
# TODO
- [x] [Supabase 문서](https://supabase.com/docs/guides/getting-started/tutorials/with-react) 확인하기
- [x] Nitter 에 올라간 Image URL 로 이미지 버퍼형식으로 다운받기
- [x] 다운받은 이미지를 Supabase Bucket Storage 에 올리기
